### ISSUE TITLE
Error Resolution in main.tex - "I couldn't open database file ./literature.bib"

### ISSUE THREAD

**Issue by marvintnk** [JanRother/template-thesis-ostfalia#1]
**Subject: Error Resolution in main.tex**

**ERROR**: "I couldn't open database file ./literature.bib"

To address the error in main.tex, simply change **line** **55** from:

`"\bibliography{./literature.bib}"`
to:
`"\bibliography{literature}"`

This adjustment resolves the issue by correcting the bibliography path format.

**Comment by JanRother** [comment]
Resolved with [migration from natbib to biblatex](https://github.com/JanRother/template-thesis-ostfalia/commit/e78a52eda0973a5f6ba3d951f00fec479fc8fa7e).
