### ISSUE TITLE
Update Author's Contact Information

### ISSUE THREAD

**Issue by NormalErik** [JanRother/template-thesis-ostfalia#4]
📧 Update Author's Contact Information

**Description**
The author's email address will be changing soon, and all relevant documentation, configuration files, and metadata need to be updated to reflect the new address.

**Details**
- **Current Email Address:** jan.rother@ostfalia.de
- **New Email Address:** NineInchMale@janrother.de

**Affected Areas**
- README files
- Code comments that reference the email
- Git commit authorship, if applicable

**Comment by JanRother** [comment]
Resolved with [update documentation](https://github.com/JanRother/template-thesis-ostfalia/commit/7381d7cdbc22e0b7849805df593a3271eb0ef7f6).

Updated contact information is provided at [template-thesis-ostfalia/README.md](https://github.com/JanRother/template-thesis-ostfalia/blob/main/README.md).
Further information were updated or added, including the [Repository Structure](https://github.com/JanRother/template-thesis-ostfalia?tab=readme-ov-file#structure), the [DevContainer Guide](https://github.com/JanRother/template-thesis-ostfalia?tab=readme-ov-file#devcontainer) and [instructions on how do deal with Git LFS](https://github.com/JanRother/template-thesis-ostfalia?tab=readme-ov-file#repository).
